services:
  rasat-analyzer:
    build: .
    container_name: rasat_scoring
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host" # สำหรับ Linux จะช่วยให้ต่อ Display ง่ายขึ้น
